services:
  litterbox-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./content:/app/content
      - ./faiss_index:/app/faiss_index
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    restart: always